######################################################################
#
# File name : TB_MODULE_wave.do
# Created on: Tue Dec 17 13:59:45 CET 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
