######################################################################
#
# File name : TB_MODULE_compile.do
# Created on: Wed Dec 18 09:14:48 CET 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom -64 -93 -work xil_defaultlib  \
"../../../../Uebung9_vhdlsync02.srcs/sources_1/imports/hdl/module.vhd" \
"../../../../Uebung9_vhdlsync02.srcs/sim_1/imports/hdl/tb_module.vhd" \


